name: website-local
recipe: lemp
config:
  php: '7.4'
  webroot: web/public
  database: mariadb
  xdebug: true
  config:
    vhosts: config/nginx.conf

proxy:
  mailhog:
    - mail.website-local.lndo.site

services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
